version: 0.8.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore meka/srcs/projects/msvc/meka.sln
build:
  project: meka/srcs/projects/msvc/meka.sln
  verbosity: minimal
after_build:
- cmd: >-
    pushd meka

    7z a ..\mekaw-%APPVEYOR_BUILD_VERSION%.zip Data Themes meka.* mekaw.exe icons.zip changes.txt debugger.txt setup.bat multi.txt tech.txt compat.txt
artifacts:
- path: '*.zip'